version: '3.8'

services:
  # The Python Backend Service
  backend:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose port 8000 for the API
    env_file:
       - ./.env

  # The React Frontend Service (served with Nginx)
  frontend:
    build:
      context: ./frontend # Look for a Dockerfile in the ./frontend directory
    volumes:
      # Mount our custom nginx config.
      # This overwrites the default config inside the container.
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80" # Map host port 3000 to the container's port 80
    depends_on:
      - backend # Tells Docker to start the backend before the frontend