name: Trigger auto deployment for bakasura

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ user-data-agent02 ]
    paths:
    - '**'
    - '.github/workflows/bakasura-AutoDeployTrigger-abe6f9b1-e846-4f78-bd0a-64a2b64b0f6f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BAKASURA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BAKASURA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BAKASURA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: bakasura.azurecr.io
          registryUsername: ${{ secrets.BAKASURA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BAKASURA_REGISTRY_PASSWORD }}
          containerAppName: bakasura
          resourceGroup: MyAgentResourceGroup
          imageToBuild: bakasura.azurecr.io/bakasura:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


